/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usdcSol from "./USDC.sol";
export type { usdcSol };
export type { MockOracle } from "./MockOracle";
export type { SingletonFactory } from "./SingletonFactory";
