/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as usdcSol from "./USDC.sol";
export { MockOracle__factory } from "./MockOracle__factory";
export { SingletonFactory__factory } from "./SingletonFactory__factory";
